04-Fundamentos-do-ASP.NET-MVC/MinhaAppFuncional/src/AppMvcFuncional/Models/Aluno.cs
using Microsoft.AspNetCore.Components.Forms;
using System.ComponentModel.DataAnnotations; // Importado para usar as anotações de validação (DataAnnotations)
using System.ComponentModel.DataAnnotations.Schema;

namespace AppMvcFuncional.Models
{
    public class Aluno
    {
        [Key] // Chave da Model
        public int Id { get; set; }

        [Required(ErrorMessage = "0 campo {0} é obrigatório")]
        [StringLength(30, MinimumLength = 2, ErrorMessage = "0 campo {0} precisa ter entre {2} e {1} caracteres")]
        public string? Nome { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        [DataType(DataType.DateTime, ErrorMessage = "O campo {0} está em formato incorreto")]
        [Display(Name = "Data de Nascimento")]
        public DateTime DataNascimento { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        [StringLength(60, ErrorMessage = "0 campo {0} precisa ter no máximo {1} caracteres")]
        [RegularExpression(@"^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$", ErrorMessage = "0 campo {0} está em formato inválido.")]
        //[EmailAddress(ErrorMessage = "O campo {0} está em formato inválido.")] - 2 formas de validar o e-mail
        public string? Email { get; set; }

        [Required(ErrorMessage = "0 campo {0} é obrigatório")]
        [Display(Name = "Confirme o e-mail")]
        [Compare("Email", ErrorMessage = "Os e-mails informados não são identicos")]
        [NotMapped] // Não mapear para o banco de dados
        public string? EmailConfirmacao { get; set; }

        [Required(ErrorMessage = "0 campo {0} é obrigatório")]
        [Range(1, 5, ErrorMessage = "O campo {0} deve estar entre {1} e {2}")]
        public int Avaliacao { get; set; }

        public bool Ativo { get; set; }
    }
}

04-Fundamentos-do-ASP.NET-MVC/MinhaAppFuncional/src/AppMvcFuncional/Models/ErrorViewModel.cs
namespace AppMvcFuncional.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

04-Fundamentos-do-ASP.NET-MVC/MinhaAppFuncional/src/AppMvcFuncional/Controllers/AlunosController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using AppMvcFuncional.Data;
using AppMvcFuncional.Models;
using Microsoft.AspNetCore.Authorization;

namespace AppMvcFuncional.Controllers
{
    [Authorize]
    [Route("meus-alunos")]
    public class AlunosController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AlunosController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Alunos
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            ViewBag.Sucesso = "Listagem bem sucedida!"; // Mensagem de sucesso para a listagem

            return _context.Aluno != null ?
                        View(await _context.Aluno.ToListAsync()) :
                        Problem("Entity set 'ApplicationDbContext.Aluno'  is null.");            
        }


        // GET: Alunos/Details/5
        [Route("detalhes/{id:int?}")]
        public async Task<IActionResult> Details(int id)
        {
            if (_context.Aluno == null)
            {
                return NotFound();
            }

            var aluno = await _context.Aluno
                .FirstOrDefaultAsync(m => m.Id == id);
            
            if (aluno == null)
            {
                return NotFound();
            }

            return View(aluno);
        }


        // GET: Alunos/Create
        [Route("novo")]
        public IActionResult Create()
        {
            return View();
        }


        // POST: Alunos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost("novo")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,DataNascimento,Email,EmailConfirmacao,Avaliacao,Ativo")] Aluno aluno)
        {
            if (ModelState.IsValid)
            {
                _context.Add(aluno);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(aluno);
        }


        // GET: Alunos/Edit/5
        [Route("editar/{id:int}")]
        public async Task<IActionResult> Edit(int id)
        {
            if (_context.Aluno == null)
            {
                return NotFound();
            }

            var aluno = await _context.Aluno.FindAsync(id);
            
            if (aluno == null)
            {
                return NotFound();
            }
            return View(aluno);
        }


        // POST: Alunos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost("editar/{id:int}")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,DataNascimento,Email,Avaliacao,Ativo")] Aluno aluno)
        {
            if (id != aluno.Id)
            {
                return NotFound();
            }

            ModelState.Remove("EmailConfirmacao"); // Remove a validação do campo EmailConfirmacao, pois não é necessário no Edit   

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(aluno);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AlunoExists(aluno.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                TempData["Sucesso"] = "Aluno editado com sucesso!"; // Mensagem de sucesso

                return RedirectToAction(nameof(Index));
            }
            return View(aluno);
        }


        // GET: Alunos/Delete/5
        [Route("excluir/{id:int}")]
        public async Task<IActionResult> Delete(int id)
        {
            if (_context.Aluno == null)
            {
                return NotFound();
            }

            var aluno = await _context.Aluno
                .FirstOrDefaultAsync(m => m.Id == id);
            if (aluno == null)
            {
                return NotFound();
            }

            return View(aluno);
        }


        // POST: Alunos/Delete/5
        [HttpPost("excluir/{id:int}"), ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Aluno == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Aluno'  is null.");
            }

            var aluno = await _context.Aluno.FindAsync(id);
            if (aluno != null)
            {
                _context.Aluno.Remove(aluno);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AlunoExists(int id)
        {
            return _context.Aluno.Any(e => e.Id == id);
        }
    }
}

04-Fundamentos-do-ASP.NET-MVC/MinhaAppFuncional/src/AppMvcFuncional/Controllers/HomeController.cs
using System.Diagnostics;
using AppMvcFuncional.Models;
using Microsoft.AspNetCore.Mvc;

namespace AppMvcFuncional.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

04-Fundamentos-do-ASP.NET-MVC/MinhaAppFuncional/src/AppMvcFuncional/Views/Alunos/Create.cshtml
@model AppMvcFuncional.Models.Aluno

@{
    ViewData["Title"] = "Cadastrar novo aluno";
}

<h1>@ViewData["Title"]</h1>

<h4>Preencha os dados corretamente</h4>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <label asp-for="DataNascimento" class="control-label"></label>
                <input asp-for="DataNascimento" class="form-control" />
                <span asp-validation-for="DataNascimento" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="EmailConfirmacao" class="control-label"></label>
                <input asp-for="EmailConfirmacao" class="form-control" />
                <span asp-validation-for="EmailConfirmacao" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Avaliacao" class="control-label"></label>
                <input asp-for="Avaliacao" class="form-control" />
                <span asp-validation-for="Avaliacao" class="text-danger"></span>
            </div>
            
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Ativo" /> @Html.DisplayNameFor(model => model.Ativo)
                </label>
            </div>
            
            <div class="form-group">
                <input type="submit" value="ENVIAR" class="btn btn-info" />
                <a asp-action="Index" class="btn btn-warning">VOLTAR</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

04-Fundamentos-do-ASP.NET-MVC/MinhaAppFuncional/src/AppMvcFuncional/Views/Alunos/Delete.cshtml
@model AppMvcFuncional.Models.Aluno

@{
    ViewData["Title"] = $"Excluir aluno {Model.Nome}";
}

<h1>@ViewData["Title"]</h1>

<h3>Tem certeza que deseja excluir o aluno @Model.Nome?</h3>
<hr />

<div>
    <h4>Aluno</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataNascimento)
        </dt>
        <dd class = "col-sm-10">            
            @* @Html.DisplayFor(model => model.DataNascimento) *@
            @Model.DataNascimento.ToString("dd/MM/yyyy")
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Avaliacao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Avaliacao)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ativo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ativo)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="EXCLUIR" class="btn btn-danger" /> 
        <a asp-action="Index" class="btn btn-warning">VOLTAR</a>
    </form>
</div>

04-Fundamentos-do-ASP.NET-MVC/MinhaAppFuncional/src/AppMvcFuncional/Views/Alunos/Details.cshtml
@model AppMvcFuncional.Models.Aluno

@{
    ViewData["Title"] = $"Detalhes do aluno {Model.Nome}";
}

<h1>@ViewData["Title"]</h1>
<hr />  

<div>
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataNascimento)
        </dt>
        <dd class = "col-sm-10">
            @* @Html.DisplayFor(model => model.DataNascimento) *@
            @Model.DataNascimento.ToString("dd/MM/yyyy")
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Avaliacao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Avaliacao)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ativo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ativo)
        </dd>
    </dl>
</div>
<div>
    <a class="btn btn-warning" asp-action="Edit" asp-route-id="@Model?.Id">EDITAR</a> 
    <a class="btn btn-info" asp-action="Index">VOLTAR</a>
</div>

04-Fundamentos-do-ASP.NET-MVC/MinhaAppFuncional/src/AppMvcFuncional/Views/Alunos/Edit.cshtml
@model AppMvcFuncional.Models.Aluno

@{
    ViewData["Title"] = "Editar aluno";
}

<h1>@ViewData["Title"]</h1>

<h4>Dados do aluno @Model.Nome</h4>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
           
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <label asp-for="DataNascimento" class="control-label"></label>
                <input asp-for="DataNascimento" class="form-control" />
                <span asp-validation-for="DataNascimento" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                <label asp-for="Avaliacao" class="control-label"></label>
                <input asp-for="Avaliacao" class="form-control" />
                <span asp-validation-for="Avaliacao" class="text-danger"></span>
            </div>
            
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Ativo" /> @Html.DisplayNameFor(model => model.Ativo)
                </label>
            </div>
            
            <div class="form-group">
                <input type="submit" value="EDITAR" class="btn btn-info" />
                <a asp-action="Index" class="btn btn-warning">VOLTAR</a>                
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

04-Fundamentos-do-ASP.NET-MVC/MinhaAppFuncional/src/AppMvcFuncional/Views/Alunos/Index.cshtml
@model IEnumerable<AppMvcFuncional.Models.Aluno>

@{
    ViewData["Title"] = "Lista de alunos";
}

<h1>@ViewData["Title"]</h1>


@if (TempData["Sucesso"] != null || ViewData["Sucesso"] != null) 
{
    var mensagem = TempData["Sucesso"] != null ? TempData["Sucesso"] : ViewData["Sucesso"];

    <div style="padding-top: 15px"></div>

    <div id="msg-box" class="alert alert-success">
        <h4 id="msgRetorno">@Html.Raw(mensagem)</h4>
    </div>
}


<p>
    <a class="btn btn-primary" asp-action="Create"><span class="fa fa-plus"></span>NOVO</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataNascimento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Avaliacao)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ativo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @item.DataNascimento.ToString("dd/MM/yyyy")
                @* @Html.DisplayFor(modelItem => item.DataNascimento) *@
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Avaliacao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ativo)
            </td>
            <td>
                <a asp-action="Details" class="btn btn-warning" asp-route-id="@item.Id"><spam class="fa fa-search"></spam></a> 

                <a asp-action="Edit" class="btn btn-info" asp-route-id="@item.Id"><spam class="fa fa-pencil-alt"></spam></a> 

                <a asp-action="Delete" class="btn btn-danger" asp-route-id="@item.Id"><spam class="fa fa-trash"></spam></a>
            </td>
        </tr>
}
    </tbody>
</table>

04-Fundamentos-do-ASP.NET-MVC/MinhaAppFuncional/src/AppMvcFuncional/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4"><i class="fa-solid fa-code"></i>Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

04-Fundamentos-do-ASP.NET-MVC/MinhaAppFuncional/src/AppMvcFuncional/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AppMvcFuncional</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AppMvcFuncional.styles.css" asp-append-version="true" />
    
    <!-- Em desenvolvimento, usar arquivo local-->
    <environment include="Development">
        <link href="~/lib/font-awesome/all.min.css" rel="stylesheet" />
    </environment>

    <environment exclude="Development">        
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" rel="stylesheet" />
    </environment>
    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AppMvcFuncional</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Alunos" asp-action="Index">Alunos</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - AppMvcFuncional - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>